lnet: eliminate uninitialized warning
lustre-release/net/lnet/lnet/router.c: In funciton 'lnet_del_route':
include/linux/compiler.h:177:26: error: 'lp' may be used uninitialized
in this function [-Werror=maybe-uninitialized]
  case 8: *(__u64 *)res = *(volatile __u64 *)p; break;  \

lustre-release/net/lnet/lnet/router.c:754:20: note: 'lp' was declared here
  struct lnet_peer *lp;

lustre-release/net/lnet/lnet/router.c: At top level:
cc1: error: unrecognized command line option '-Wno-stringop-overflow' [-Werror]
cc1: error: unrecognized command line option '-Wno-stringop-truncation' [-Werror]
cc1: error: unrecognized command line option '-Wno-format-truncation' [-Werror]
cc1: all warnings being treated as errors

codes logic gurantee @lpi and @lpni are inited at the same time,
but let's init @lpi to make gcc happy.

WC-bug-id: https://jira.whamcloud.com/browse/LU-12764
Lustre-commit: a8fbaa1b998f ("LU-12764 lnet: eliminate uninitialized warning")
Signed-off-by: Wang Shilong <wshilong@ddn.com>
Reviewed-on: https://review.whamcloud.com/36189
Reviewed-by: Andreas Dilger <adilger@whamcloud.com>
Reviewed-by: Li Dongyang <dongyangli@ddn.com>
Reviewed-by: Oleg Drokin <green@whamcloud.com>
Signed-off-by: James Simmons <jsimmons@infradead.org>